apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-plus-config
  namespace: nginx
data:
  nginx.conf: |

    user  nginx;
    worker_processes auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    load_module modules/ngx_http_js_module.so;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        js_import /usr/share/nginx-plus-module-prometheus/prometheus.js;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        keepalive_timeout  65;


    }